CREATE TABLE CATEGORIA
(
  ID   BIGINT AUTO_INCREMENT
    PRIMARY KEY,
  NOME VARCHAR(255) NULL,
  CONSTRAINT CATEGORIA_NOME_UN
  UNIQUE (NOME)
)
  ENGINE = InnoDB;

CREATE TABLE PRODUTO
(
  ID            BIGINT AUTO_INCREMENT
    PRIMARY KEY,
  CATEGORIA_ID  BIGINT       NOT NULL,
  DATA_CADASTRO DATE         NULL,
  DATA_VENDA    DATE         NULL,
  NOME          VARCHAR(255) NULL,
  CONSTRAINT PRODUTO_CATEGORIA_FK
  FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID)
)
  ENGINE = InnoDB;

CREATE INDEX PRODUTO_CATEGORIA_FK
  ON PRODUTO (CATEGORIA_ID);

